version: '3'
services:
  web:
    depends_on:
     - db
    restart: always
    image: localhost:5000/my-web:latest
    ports:
     - "8080:80"
  
  db:
    build:
      context: ./db
    volumes: 
      - db_data:/data
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
    deploy:
      mode: replicated
      replicas: 6
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  db_data:
 